apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinica-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clinica-backend
  template:
    metadata:
      labels:
        app: clinica-backend
    spec:
      containers:
        - name: clinica-backend
          image: poguis/clinica-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/ProyectoClinica?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"