FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=proyectoclinica
ENV MYSQL_ROOT_HOST=%

COPY init.sql /docker-entrypoint-initdb.d/

# Configuraciones adicionales de MySQL
COPY my.cnf /etc/mysql/conf.d/

# Establecer permisos
RUN chmod 644 /etc/mysql/conf.d/my.cnf \
    && chmod 644 /docker-entrypoint-initdb.d/init.sql \
    && chown -R mysql:mysql /docker-entrypoint-initdb.d/ \
    && chown -R mysql:mysql /etc/mysql/conf.d/ 