FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=proyectoclinica

COPY init.sql /docker-entrypoint-initdb.d/

# Configuraciones adicionales de MySQL
COPY my.cnf /etc/mysql/conf.d/

# Establecer permisos
RUN chown -R mysql:mysql /docker-entrypoint-initdb.d/ 