apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: grupo4espe/clinica-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://backend:8080
        resources:
          requests:
            memory: "256Mi"  # Memoria mínima que el contenedor solicita
            cpu: "250m"      # CPU mínima que el contenedor solicita (250 milicores)
          limits:
            memory: "512Mi"  # Límite máximo de memoria que el contenedor puede usar
            cpu: "500m"      # Límite máximo de CPU que el contenedor puede usar (500 milicores)