name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Test Backend
        run: |
          cd ProyectoClinica
          mvn clean package -DskipTests

      - name: Run Integration Tests
        run: |
          cd ProyectoClinica
          mvn test

      - name: Build and Test Frontend
        run: |
          cd clinica_frontend
          npm install
          npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          cd ProyectoClinica
          docker build -t tu-dockerhub-username/clinica-backend:latest .
          docker push tu-dockerhub-username/clinica-backend:latest

      - name: Build and Push Frontend Image
        run: |
          cd clinica_frontend
          docker build -t tu-dockerhub-username/clinica-frontend:latest .
          docker push tu-dockerhub-username/clinica-frontend:latest

      - name: Deploy to GKE
        run: |
          echo "${{ secrets.GKE_KEY }}" | base64 --decode > gke-key.json
          gcloud auth activate-service-account --key-file=gke-key.json
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}
          kubectl apply -f k8s/