name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Build backend with Maven
        run: |
          cd ProyectoClinica
          mvn clean package -DskipTests
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./ProyectoClinica
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clinica-backend:latest

  build-mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push MySQL image
        uses: docker/build-push-action@v4
        with:
          context: ./Database
          file: ./Database/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clinica-mysql:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies and build frontend
        run: |
          cd clinica_frontend
          npm install
          export CI=false
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./clinica_frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clinica-frontend:latest

  deploy:
    needs: [build-backend, build-mysql, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        
      - name: Deploy to Kubernetes
        run: |
          # Limpiar recursos existentes
          kubectl delete deployments,services,pvc --all || true
          
          # Aplicar configuraciones
          kubectl apply -f k8s/mysql-pvc.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml
          
          echo "Waiting for MySQL to be ready..."
          kubectl wait --for=condition=ready pod -l app=mysql --timeout=300s
          
          # Verificar estado del pod MySQL
          echo "Checking MySQL pod status..."
          kubectl describe pod -l app=mysql
          kubectl logs -l app=mysql
          
          echo "Setting up MySQL database..."
          MYSQL_POD=$(kubectl get pod -l app=mysql -o jsonpath="{.items[0].metadata.name}")
          
          # Esperar a que MySQL esté realmente listo
          echo "Waiting for MySQL to be fully initialized..."
          sleep 30
          
          # Copiar y ejecutar script
          echo "Copying database script..."
          kubectl cp Database/script.sql $MYSQL_POD:/tmp/
          
          echo "Initializing database..."
          kubectl exec $MYSQL_POD -- bash -c "mysql -h localhost -P 3306 -u root -proot < /tmp/script.sql"
          
          # Desplegar backend
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          
          echo "Waiting for backend to be ready..."
          kubectl wait --for=condition=ready pod -l app=backend --timeout=300s
          
          # Desplegar frontend
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          
          echo "Waiting for frontend to be ready..."
          kubectl wait --for=condition=ready pod -l app=frontend --timeout=300s
          
          # Verificar estado final
          echo "Final deployment status:"
          kubectl get all
          
          echo "Pod logs:"
          for pod in $(kubectl get pods -o name); do
            echo "=== $pod logs ==="
            kubectl logs $pod --tail=20
          done
          
          echo "Deployment completed successfully"